export const siteConstants = {
    businessName: "ModernCraftPDX",
    businessNameShort: "ModernCraftPDX",
    businessNameLong: "ModernCraftPDX",
    businessCCB: "CCB #123456",
    businessAddress: "Portland, OR",
    businessPhone: "503-555-5555",
    businessEmail: "info@moderncraftpdx.com",
    businessWebsite: "https://moderncraftpdx.com",
    businessFacebook: "",
    businessInstagram: "",
    businessTwitter: "",
    businessYoutube: "",
    businessLinkedin: "",
}